### ISSUE TITLE
[Feature Request] NBT-Preserving Scroll Group

### ISSUE THREAD

**Issue by lucidobservor** [quat1024/zenscroll#1]
It would be useful for there to be a way to create a scroll group which preserves NBT tags across scrolls. 

The use case prompting this feature request: One can create a scroll group to scroll through different sizes of Storage Drawers (1x1 -> 1x2 -> 2x2 -> ...). However, that doesn't work for scrolling through sized of framed drawers unless scrolling can preserve NBT.

(Disclaimer: I have not actually checked that framed drawers store their framing information as NBT, it just seems like a safe assumption)

I'm imagining a method that looks like `ZenScroll.addPreservingNBT(...)`, but who knows if that's the best way to do it.

**Comment by quat1024** [comment]
Ok, I implemented this by way of a function that lets you totally customize the scrolled item.

The "long way":

```
//creating a group
var glassGroup = ScrollGroup.of(<minecraft:stained_glass:*>);

//setting the processor
glassGroup.processor(
  function(a as IItemStack, b as IItemStack) {
    return <minecraft:apple>; //returns a totally different item D:
  }
);

//registering it
ZenScroll.add(glassGroup);
```
The "short way":
```
//ZenScroll.add now returns a ScrollGroup
ZenScroll.add(<minecraft:wool:*>).copyTag(); //using the built in copyTag processor
```
